// apps/demos/Demos/HtmlEditor/AITextEditing/Angular/app/app.component.ts
import { NgModule, Component, enableProdMode } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AzureOpenAI, OpenAI } from 'openai';

import { DxHtmlEditorModule } from 'devextreme-angular';
import {
    AIIntegration,
    RequestParams,
    Response,
} from 'devextreme/common/ai-integration';

import { Service } from './app.service';

if (!/localhost/.test(document.location.host)) {
  enableProdMode();
}

let modulePrefix = '';
// @ts-ignore
if (window && window.config?.packageConfigPaths) {
  modulePrefix = '/app';
}

type AIMessage = (OpenAI.ChatCompletionUserMessageParam | OpenAI.ChatCompletionSystemMessageParam) & {
  content: string;
};

@Component({
  selector: 'demo-app',
  templateUrl: `.${modulePrefix}/app.component.html`,
  styleUrls: [`.${modulePrefix}/app.component.css`],
  providers: [Service],
})

export class AppComponent {
  azureOpenAIConfig: any;

  aiService: AzureOpenAI;

  aiIntegration: AIIntegration;

  commands: any[];

  valueContent: string;

  constructor(service: Service) {
    this.azureOpenAIConfig = service.getAzureOpenAIConfig();
    this.commands = service.getCommands();
    this.valueContent = service.getMarkup();

    this.aiService = new AzureOpenAI(this.azureOpenAIConfig);
    this.aiIntegration = new AIIntegration({
      sendRequest: this.sendRequest.bind(this),
    });
  }

  sendRequest ({ prompt }: RequestParams): Response {
    const controller = new AbortController();
    const signal = controller.signal;

    const aiPrompt: AIMessage[] = [
      { role: 'system', content: prompt.system, },
      { role: 'user', content: prompt.user, },
    ];
    const promise = this.getAIResponse(aiPrompt, signal);

    const result: Response = {
      promise,
      abort: () => {
        controller.abort();
      },
    };

    return result;
  }

  async getAIResponse(messages: AIMessage[], signal: AbortSignal) {
    const params = {
      messages,
      model: this.azureOpenAIConfig.deployment,
      max_tokens: 1000,
      temperature: 0.7,
    };

    const response = await this.aiService.chat.completions.create(params, { signal });
    const result = response.choices[0].message?.content;

    return result;
  }
}

@NgModule({
  imports: [
    BrowserModule,
    DxHtmlEditorModule,
  ],
  declarations: [AppComponent],
  bootstrap: [AppComponent],
})

export class AppModule { }

platformBrowserDynamic().bootstrapModule(AppModule);

// apps/demos/Demos/HtmlEditor/AITextEditing/Vue/App.vue
<template>
  <DxHtmlEditor
    :value="markup"
    :height="530"
    :ai-integration="aiIntegration"
  >
    <DxToolbar>
      <DxItem
        name="ai"
        :commands="commands"
      />
      <DxItem name="separator"/>
      <DxItem name="undo"/>
      <DxItem name="redo"/>
    </DxToolbar>
  </DxHtmlEditor>
</template>
<script setup lang="ts">
import { AzureOpenAI, OpenAI } from 'openai';

import {
  DxHtmlEditor,
  DxItem,
  DxToolbar,
} from 'devextreme-vue/html-editor';
import { AIIntegration } from 'devextreme/common/ai-integration';

import { 
  markup,
  commands,
  AzureOpenAIConfig,  
} from './data.ts';

type AIMessage = (OpenAI.ChatCompletionUserMessageParam | OpenAI.ChatCompletionSystemMessageParam) & {
  content: string;
};

const aiService = new AzureOpenAI(AzureOpenAIConfig);

async function getAIResponse(messages: AIMessage[], signal: AbortSignal) {
  const params = {
    messages,
    model: AzureOpenAIConfig.deployment,
    max_tokens: 1000,
    temperature: 0.7,
  };
  
  const response = await aiService.chat.completions.create(params, { signal });
  const result = response.choices[0].message?.content;

  return result;
}

const aiIntegration = new AIIntegration({
  sendRequest({ prompt }) {
    const controller = new AbortController();
    const signal = controller.signal;

    const aiPrompt: AIMessage[] = [
      { role: 'system', content: prompt.system, },
      { role: 'user', content: prompt.user, },
    ];

    const promise = getAIResponse(aiPrompt, signal);

    const result = {
      promise,
      abort: () => {
        controller.abort();
      },
    };

    return result;
  },
});

</script>
<style>
.dx-htmleditor-content img {
  vertical-align: middle;
  padding-right: 10px;
}
</style>
